name: Build, Publish and Deploy - production

on:
  push:
    branches:
      - main
      - master
      - production
      - staging
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: production
  cancel-in-progress: true

env:
  NAMESPACE: xthang
  IMAGE_NAME: data-api
  VM_IP: 15.235.184.142
  VM_USER: ubuntu
  LOCAL_PORT: 8000
  PUBLIC_PORT: 6010

jobs:
  setup-build-publish:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    environment: PRODUCTION
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.local file
        run: |
          touch .env.local

          echo '${{ vars.ENV_LOCAL_FILE }}' >> .env.local

          echo 'SENTRY_DSN=${{ secrets.SENTRY_DSN }}' >> .env.local
          echo 'DATABASE_URL=${{ secrets.DATABASE_URL }}' >> .env.local
          echo 'PRISMA_FIELD_ENCRYPTION_KEY=${{ secrets.PRISMA_FIELD_ENCRYPTION_KEY }}' >> .env.local
          echo 'CLERK_PUBLIC_KEY=${{ secrets.CLERK_PUBLIC_KEY }}' >> .env.local
          echo 'FILE_URL_DECRYPT_KEY=${{ secrets.FILE_URL_DECRYPT_KEY }}' >> .env.local
          echo 'FILE_SERVICE_SYSTEM_SYNC_API_KEY=${{ secrets.FILE_SERVICE_SYSTEM_SYNC_API_KEY }}' >> .env.local

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to Github Container Registry
        run: |
          docker buildx build . -f Dockerfile.prod --platform=linux/amd64 --build-arg CI_COMMIT_SHA=${{ github.sha }} -t ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest 
          docker push ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy to VM
    needs: setup-build-publish
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
      - name: Deploying to VM using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          # --add-host host.docker.internal:host-gateway : so that we can call to EVM localhost (eg local Database)
          script: |
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
            docker pull ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            docker logout
            docker stop ${{ env.IMAGE_NAME }} || true
            docker rm ${{ env.IMAGE_NAME }} || true
            docker run -d \
            --restart=always \
            --name ${{ env.IMAGE_NAME }} \
            --add-host host.docker.internal:host-gateway \
            -p ${{ env.PUBLIC_PORT }}:${{ env.LOCAL_PORT }} \
            ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            docker rmi $(docker images --filter=reference='ghcr.io/${{ env.NAMESPACE }}/${{ env.IMAGE_NAME }}' --filter "dangling=true" -q) || true
